manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: yangxing
      url-base: https://github.com/yangxing844
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
    - name: zmk-lpm009m360a-driver
      remote: yangxing
      revision: master
  self:
    path: config
